### PR TITLE
Adding default labels script.

### PR DESCRIPTION
**Pull request by ordavidil**
#5

### CODE REVIEW

**Comment by amitaibu** [comment]
Lets add a reference and the exact command to be used to grab and execute this script in `/issue-queue`

(e.g. `curl -s http://... | sh`)

**Comment by ordavidil** [comment]
selection_345

**Comment by amitaibu** [comment]
don't you need to `curl` the the raw link?
Also you can have this in a single command `curl -O https://... && bash default...`

**Comment by ordavidil** [comment]
selection_347

**Comment by amitaibu** [comment]
Merged, thanks.

**Comment by amitaibu** [comment]
Deployed: `gulp publish && gulp deploy`

**Pull request closed without merging**
